#!/bin/bash -v
sleep 600
export INSTANCEID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null)
while STATE=$(aws --no-verify-ssl ec2 describe-instances --region sa-east-1 --filters "Name=tag:Name,Values=Splunk-Master" "Name=instance-state-name,Values=running" --output text --query 'Reservations[*].Instances[*].State.Name'); test "$STATE" != "running"; do
    sleep 5;
    echo "Splunk-Master - Aguardando..."
done;
echo "Splunk-Master Iniciada"
aws --no-verify-ssl ec2 describe-instances --region sa-east-1 --filters "Name=tag:Name,Values=Splunk-Master" "Name=instance-state-name,Values=running" --output text --query 'Reservations[*].Instances[*].PrivateIpAddress'
export MASTER_IP=$(aws --no-verify-ssl ec2 describe-instances --region sa-east-1 --filters "Name=tag:Name,Values=Splunk-Master" | grep -oP '(?<="PrivateIpAddress": ")[^"]*' -m 1)
export LOCALIP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
export DEPLOYER_IP=$(aws --no-verify-ssl ec2 describe-instances --region sa-east-1 --filters "Name=tag:Name,Values=Splunk-Deployer" | grep -oP '(?<="PrivateIpAddress": ")[^"]*' -m 1)
export INSTANCE_MAC_ADDR=$(curl -s http://169.254.169.254/latest/meta-data/mac)
export SH_IP=$(aws --no-verify-ssl ec2 describe-instances --region sa-east-1 --filters "Name=tag:Name,Values=Splunk-Search_Head" | grep -oP '(?<="PrivateIpAddress": ")[^"]*' | sort -u)
export SH_1=$(echo $SH_IP | awk '{print $1}')
export SH_2=$(echo $SH_IP | awk '{print $2}')
export SH_3=$(echo $SH_IP | awk '{print $3}')
export ldap_pass=${ldap_password}
export admin_pass=${admin_password}
export INSTANCE_SUBNET_ID=$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$INSTANCE_MAC_ADDR/subnet-id)
case $INSTANCE_SUBNET_ID in 
${private_subnet_1}) site=site1;;
${private_subnet_2}) site=site2;;
*) echo "Unexpected subnet id";;
esac
export INSTANCEID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null)
export INSTANCE_TYPE=$(aws ec2 describe-instances --instance-id $INSTANCEID --region sa-east-1 --output text --query 'Reservations[*].Instances[*].InstanceType')
case $INSTANCE_TYPE in 
*c5d*) 
mkdir /data
sudo mkfs -t xfs /dev/nvme1n1
sudo blkid /dev/nvme1n1
UUID=$(sudo blkid /dev/nvme1n1 | grep -Po '(?s)(?<=UUID=").*?(?=")')
sudo cat >>/etc/fstab <<end
UUID=$UUID     /data       xfs    defaults,nofail   0   2
end
mount -a
chown splunk:splunk /data
;;
*i3*) 
mkdir /data
sudo mkfs -t xfs /dev/nvme0n1
sudo blkid /dev/nvme0n1
UUID=$(sudo blkid /dev/nvme0n1 | grep -Po '(?s)(?<=UUID=").*?(?=")')
sudo cat >>/etc/fstab <<end
UUID=$UUID     /data       xfs    defaults,nofail   0   2
end
mount -a
chown splunk:splunk /data
;;
*) echo "Unexpected subnet id";;
esac

sudo cat >>/home/splunk/splunk_temp.sh<<end1

#!/bin/bash -v

if [ -d "/data" ]
then
#Movimentação do SPLUNK_DB
sudo -u splunk /opt/splunk/bin/splunk stop
sudo -u splunk cp -R /opt/splunk/var/lib/splunk /data 
sudo -u splunk rm -Rf /opt/splunk/var/lib/splunk
sudo -u splunk cat >>/opt/splunk/etc/splunk-launch.conf <<END
SPLUNK_DB=/data
END

sudo -u splunk /opt/splunk/bin/splunk start
echo "Diretorio Movimentado" >> /home/splunk/splunk.log

else
echo "Diretorio Não Existe" >> /home/splunk/splunk.log
fi

#Alteração da senha de admin

sudo -u splunk mv /opt/splunk/etc/passwd /opt/splunk/etc/passwd.bak
sudo -u splunk cat >>/opt/splunk/etc/system/local/user-seed.conf<<end
[user_info]
USERNAME = admin
PASSWORD = $admin_pass
end

chown splunk:splunk /opt/splunk/etc/system/local/user-seed.conf

sudo -u splunk sed -i '/guid/d' /opt/splunk/etc/instance.cfg
sudo -u splunk touch /opt/splunk/etc/.ui_login
sudo -u splunk /opt/splunk/bin/splunk edit user admin -password '$admin_pass' -role admin -auth admin:SPLUNK-$INSTANCEID
sudo -u splunk /opt/splunk/bin/splunk add user tatico -password abcd1234 -role admin -auth admin:'$admin_pass'

echo "Alteracao senha Usuario Admin" >> /home/splunk/splunk.log

sudo /opt/splunk/bin/splunk stop

#Alteração do ulimit do Linux e adicionando o splunk no boot-start

sudo /opt/splunk/bin/splunk disable boot-start
sudo /opt/splunk/bin/splunk enable boot-start -user splunk -systemd-managed 0

echo "Adicionando Splunk no boot start" >> /home/splunk/splunk.log

sed -i '/init.d\/functions/a ulimit -Sn 32768' /etc/init.d/splunk
sed -i '/init.d\/functions/a ulimit -Hn 65536' /etc/init.d/splunk

sudo cat >>/etc/security/limits.conf<<end
#splunk
root        soft    nofile           64000
root        hard    nofile           64000
root        hard    nproc            16000
root        hard    fsize            -1  
splunk      soft    nofile           64000
splunk      hard    nofile           64000
splunk      hard    nproc            16000
splunk      hard    fsize            -1  
 
end

echo "Alteração do ulimit" >> /home/splunk/splunk.log

sudo -u splunk /opt/splunk/bin/splunk restart

echo "Restart 1" >> /home/splunk/splunk.log

#Alteração do Servername
sudo -u splunk /opt/splunk/bin/splunk set servername $HOSTNAME -auth admin:'$admin_pass'

echo "Altera ServerName" >> /home/splunk/splunk.log


#Aumento do tempo de timeout e habilitição de SSL
touch /opt/splunk/etc/system/local/web.conf
sudo cat >>/opt/splunk/etc/system/local/web.conf <<end
[settings]
splunkdConnectionTimeout = 300
enableWebDebug = True
enableSplunkWebSSL = True

end

chown splunk:splunk /opt/splunk/etc/system/local/web.conf

echo "Altera WebService" >> /home/splunk/splunk.log

# Habilitar o index auto discovery

touch /opt/splunk/etc/system/local/outputs.conf
sudo cat >>/opt/splunk/etc/system/local/outputs.conf <<end
# Turn off indexing on the search head
[indexAndForward]
index = false

[tcpout]
defaultGroup = indexer_cluster_peers
forwardedindex.filter.disable = true
indexAndForward = false

[tcpout:indexer_cluster_peers]
indexerDiscovery = cluster_master

[indexer_discovery:cluster_master]
pass4SymmKey = $admin_pass
master_uri = https://$MASTER_IP:8089

end

echo "Indicação das Indexers" >> /home/splunk/splunk.log

chown splunk:splunk /opt/splunk/etc/system/local/outputs.conf

sudo -u splunk cat >>/opt/splunk/etc/system/local/server.conf <<end
[shclustering]
register_replication_address = $LOCALIP

[indexer_discovery]
pass4SymmKey = $admin_pass
indexerWeightByDiskCapacity = true

end

echo "Adicionando Informações do cluster" >> /home/splunk/splunk.log

chown -R splunk:splunk /opt/splunk/

sudo -u splunk /opt/splunk/bin/splunk restart

echo "Restart 2" >> /home/splunk/splunk.log

#Indicação da license master

sudo -u splunk /opt/splunk/bin/splunk edit licenser-localslave -master_uri https://$MASTER_IP:8089 -auth admin:'$admin_pass' &>> /home/splunk/splunk.log

echo "Indicando License Master" >> /home/splunk/splunk.log

#Adicionando no cluster de search head

sudo -u splunk /opt/splunk/bin/splunk edit cluster-config -secret '$admin_pass' -mode searchhead -site $site -master_uri https://$MASTER_IP:8089 -auth admin:'$admin_pass' &>> /home/splunk/splunk.log

echo "Criando cluster de SH" >> /home/splunk/splunk.log

sudo -u splunk /opt/splunk/bin/splunk restart

echo "Restart 3" >> /home/splunk/splunk.log

#Indicação da deployer

sudo -u splunk /opt/splunk/bin/splunk init shcluster-config -mgmt_uri https://$LOCALIP:8089 -replication_port 8090 -replication_factor 3  -conf_deploy_fetch_url https://$DEPLOYER_IP:8089 -shcluster_label SplunkSHC -secret '$admin_pass' -auth admin:'$admin_pass' &>> /home/splunk/splunk.log

echo "Indica Deployer" >> /home/splunk/splunk.log

sudo -u splunk cat >>/opt/splunk/etc/system/local/authorize.conf<<end
[role_fh5 user]
cumulativeRTSrchJobsQuota = 0
cumulativeSrchJobsQuota = 0
importRoles = user
rtSrchJobsQuota = 1
srchIndexesAllowed = raw_caronte
srchIndexesDefault = raw_caronte
srchMaxTime = 8640000

[role_fc7 user]
cumulativeRTSrchJobsQuota = 0
cumulativeSrchJobsQuota = 0
importRoles = user
rtSrchJobsQuota = 1
srchIndexesAllowed = raw_caronte
srchIndexesDefault = raw_caronte
srchMaxTime = 8640000
end

sudo -u splunk cat >>/opt/splunk/etc/system/local/authentication.conf<<end
[authentication]
authSettings = LDAP ITAU
authType = LDAP

[LDAP ITAU]
SSLEnabled = 0
anonymous_referrals = 1
bindDN = ${ldap_user}
bindDNpassword = \\$ldap_pass
charset = utf8
emailAttribute = mail
enableRangeRetrieval = 0
groupBaseDN = DC=itau,DC=corp,DC=ihf
groupBaseFilter = (&(objectClass=Group)(|(cn=G_CLOUD_TOOLS_GIT_IM2TATICO_DEVELOPER)(cn=G_PRD_FH5_SPLUNK)(cn=G_PRD_FC7_SPLUNK)(cn=G_PRD_IM2_SPLUNK_CAPABILITIES)))
groupMappingAttribute = distinguishedname
groupMemberAttribute = member
groupNameAttribute = cn
host = ldap.itau.corp.ihf
nestedGroups = 0
network_timeout = 20
pagelimit = -1
port = 389
realNameAttribute = displayname
sizelimit = 10000
timelimit = 15
userBaseDN = DC=itau,DC=corp,DC=ihf
userNameAttribute = samaccountname

[roleMap_LDAP ITAU]
admin = G_CLOUD_TOOLS_GIT_IM2TATICO_DEVELOPER
admin = G_PRD_IM2_SPLUNK_CAPABILITIES
fh5 user = G_PRD_FH5_SPLUNK
fc7 user = G_PRD_FC7_SPLUNK
end

sleep 1000

echo "LDAP configurado" >> /home/splunk/splunk.log

sudo -u splunk /opt/splunk/bin/splunk restart

echo "Restart 4" >> /home/splunk/splunk.log

if [ "$LOCALIP" == "$SH_1" ]; then
sleep 300
sudo -u splunk /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://$SH_1:8089,https://$SH_2:8089,https://$SH_3:8089" -auth admin:'$admin_pass' &>> /home/splunk/splunk.log
echo "Cria cluster SH" >> /home/splunk/splunk.log

sudo -u splunk /opt/splunk/bin/splunk rolling-restart shcluster-members &>> /home/splunk/splunk.log

echo "Restart do cluster de SH iniciado" >> /home/splunk/splunk.log

else
    echo "Não é a capita" >> /home/splunk/splunk.log
fi

rm -f /home/splunk/splunk_temp.sh

echo "remove splunk_temp.sh" >> /home/splunk/splunk.log

end1

chmod 777 /home/splunk/splunk_temp.sh

at -f /home/splunk/splunk_temp.sh now + 12 minute
